### ISSUE TITLE
Can't detect my F21 Pro 32gb 3gb ram

### ISSUE THREAD

**Issue by funtikar** [MlgmXyysd/F21ProInjector#2]
"No Qin F21 Pro device detected, please connect to PC............."

I am testing your script on MacOS catalina
I have tested ADB SHELL and ADB DEVICES works nicely outside of the script

**Comment by MlgmXyysd** [comment]
It may have been fixed in https://github.com/MlgmXyysd/F21ProInjector/commit/eb9f822c0923ed5847d5bd255890bc711f1a69c7.
